### PR TITLE
Add known cheaters to mute list

### LINKED ISSUE #13: Link with mute list
Link the list of known cheaters with the voice_ban.dt file.

### PR DESCRIPTION
**Pull request by noneucat**
Adds a button to the Settings panel that, when pressed, will add players that are marked cheaters to TF2's `voice_ban.dt`.

Fixes #13.

**TODO:**
- [x] Glue code: Add button to sync cheater IDs to mute list
- [x] Add warning (must sync before starting game)
- [x] Update .vcxproj

### CODE REVIEW

**Comment by noneucat** [comment]
Ready for review.
Screenshots: https://imgur.com/a/M29PSmt

**Comment by ClusterConsultant** [comment]
This seems to be dead and currently has conflicts. If you are currently working on this please let us know. If not please close the pull request. Contributions are always appreciated but code quality is very important for open source projects. This may be closed in the near future due to staleness.

**Comment by noneucat** [comment]
I'm really not interested in contributing to a project that (1) bans members from Discord for no reason, (2) calls other people "noob programmers". This sort of hostility to contribution goes against the spirit of the [GitHub Community Guidelines](https://help.github.com/articles/github-community-guidelines).

I agree that this is not best practice for namespacing, and I agree there are spacing issues. Fixable; but no thanks.

**Comment by PazerOP** [comment]
@noneucat, I apologize for the behavior of @Chrissucks. He is not affiliated with this project in any way, and because of the way he left his comments on this pull request, I cannot delete them. He was blocked as soon as it became obvious he was here to create a hostile environment (which is to say, shortly after he left these comments). With regards to bans on discord, I encourage anyone who feels they have been wrongly banned to DM me on discord: pazer#8137.

**Pull request closed without merging**
