### PR TITLE
QOL update for all

### PR DESCRIPTION
**Pull request by d3fc0n6**
how does one miss this

### CODE REVIEW

**Comment by PazerOP** [comment]
i'll think about it

**Comment by incontestableness** [comment]
LGTM
scroll

**Comment by PazerOP** [comment]
still thinkin about it

**Comment by incontestableness** [comment]
dance

**Comment by d3fc0n6** [comment]
it's super important I suggest you come to a decision soon

**Comment by undnull** [comment]
The hero we all need but don't deserve

**Comment by PazerOP** [comment]
decided against it, sorry

**Comment by undnull** [comment]
Sad

**Comment by SinnerTF2** [comment]
im not a human

**Comment by d3fc0n6** [comment]
Literally 1985

**Pull request closed without merging**
