### PR TITLE
Added more bot names to the rules, (slightly) better racism detection in the rules, 2 suspected cheaters (marked suspicious) to the playerlist and a confirmed cheater to the playerlist

### PR DESCRIPTION
**Pull request by Hedwig7s**

### CODE REVIEW

**Comment by Hedwig7s** [comment]
You have a decent chance of catching the bots added to the ruleset and you will probably find the guys added to the playerlist between 18:00-21:00 CEST (2fort)

**Review by ClusterConsultant — CHANGES_REQUESTED** [review]
Firstly, this project does not accept community submissions to the playerlist of any form.

Secondly, we are not settled on expanding the racism tag, see issue #246 and the discord for more discussion.

Thirdly, rule marks on name alone should ideally either be incredibly high confidence (e.g. something that is impossible for a standard user, like new lines) or use the transient mark system to reduce the amount of harm caused by a erroneous mark.

Lastly, which region are these bots active? I can recall seeing a few of them a while back but as far as I've seen they are not present in NA.

**Comment by Hedwig7s** [comment]
CEST

**Comment by Hedwig7s** [comment]
Anyway closed now so you can do it

**Pull request closed without merging**
