### PR TITLE
Fixed shit code

### PR DESCRIPTION
**Pull request by ProjectOdium**
It's not good, you should just rewrite it starting from this commit, you picked a shit tech stack and you wrote it really badly. You are not even remotely a skilled programmer or even close enough to smart to tackle a project like this

Try again

### CODE REVIEW

**Comment by Scarlette564** [comment]
How about instead of attacking the creator, you give tips on how to make it better or fix it? Insulting doesn't help at all, thanks.

**Comment by GolfinhoVoador** [comment]
> How about instead of attacking the creator, you give tips on how to make it better or fix it? Insulting doesn't help at all, thanks.

Just noticed he deleted a bunch of files, like +11k lines

**Comment by RonSkons** [comment]
Still works great though 😄

**Comment by leighmacdonald** [comment]
Its just a dumb troll wasting his own time.

Besides, you cant trust the opinion of anyone who willingly uses 1-based index languages :)

**Comment by PazerOP** [comment]
Thanks, I'll consider this for a later version. Keep up the good work!

**Pull request closed without merging**
