### PR TITLE
Update rules.official.json

### PR DESCRIPTION
**Pull request by moebkun**
Added [VALVE]nkiller and Cheemsburger gaming to the rules
with these added to the official rules should have the majority of current bots covered

### CODE REVIEW

**Comment by PazerOP** [comment]
* At most, "cheemsburger gaming" should just mark those users as suspicious. Anyone might set their name to that, similar to how you still see legitimate players today with the name "engineer gaming".
* Is it just a better idea to mark people with `[VALVE]` and `[VAC]` in their name? Is it at all possible to have those in your name without cheating?

**Comment by moebkun** [comment]
Psure cheemsburger gaming is bots and have been around for quite some time.

And as for valve and vac, its easy to get that in your name with just [VAL%VE] or [VA%C] as the TF2 engine does not render %.

**Comment by delimeats-ch** [comment]
It's only been like a week
But congratulations, the name has already changed

**Comment by moebkun** [comment]
meh can be closed I guess

**Pull request closed without merging**
