### PR TITLE
add char that nullcore uses to namestealing check

### PR DESCRIPTION
**Pull request by sapphonie**

### CODE REVIEW

**Comment by stephanieLGBT** [comment]
keep in mind that steam allows you to input this character in your name so it might false pos ppl who arent using external cheat programs, but it definitely still works for name stealing

https://www.fileformat.info/info/unicode/char/0e4a/index.htm

**Comment by The-personified-devil** [comment]
I don't think this should be implemented, because it could cause false positives, which is to be avoided. Especially now that valve basically killed the name stealing problem. Please close this.
Thanks

**Comment by ClusterConsultant** [comment]
Avoiding false positives is very important to maintain trust within the community. Given this is a valid character I too think this should not be added.

**Comment by PazerOP** [comment]
As far as I know this check doesn't get triggered much anymore, if at all. The bots seem to have stopped simply appending it to their name, and instead randomly insert the character somewhere in the middle. Also, 0x0E4A seems to be a valid Thai character ("thai character mai tri"), while a 0x200f ("right-to-left mark") is much less likely to be included in Steam nicknames. I don't think it's worth adding this character.

**Comment by sapphonie** [comment]
absolutely fair, cheers

**Pull request closed without merging**
