### PR TITLE
Discord rich presence

### PR DESCRIPTION
**Pull request by Haxorzz**
Will this ever be implemented into the main branch? And does it have any diffrences?

### CODE REVIEW

**Comment by PazerOP** [comment]
It will be implemented after v1.1 is released.

**Comment by Haxorzz** [comment]
Aight we're locked and loaded!

**Comment by doot0** [comment]
I'm curious; why does a bot detector need to utilise Discord Rich Presence?

**Comment by PazerOP** [comment]
It doesn't, I just wanted rich presence in TF2 and the design of tf2bd means that 90% of the work is already done.

**Pull request merged**
