### PR TITLE
Send commands directly to game instead of using -hijack

### PR DESCRIPTION
**Pull request by notroboot**
Whats up big paz

Instead of launching a new temporary instance of TF2 every time you want to add a command to the command buffer, you can do it directly by sending a window message (`WM_COPYDATA`) containing the command string.

This is actually how `-hijack` works internally: https://github.com/TheAlePower/TeamFortress2/blob/1b81dded673d49adebf4d0958e52236ecc28a956/tf2_src/launcher/launcher.cpp#L1375

This will fix those errors at the bottom of the readme that some users are getting. Also, it's probably faster 'cause you don't have to create a new process.

-Roboot

### CODE REVIEW

**Comment by Chrissucks** [comment]
its almost like paz isn't a c++ developer

**Comment by notroboot** [comment]
@PazerOP I go out of my way to try and improve your software and my reward is a ban from the Discord server? What's up with that?

**Comment by CoolcGuy** [comment]
he pulled a yandere dev lmao

**Comment by noneucat** [comment]
@notroboot I just got kicked immediately after pinging him with a PR

???

**Comment by KingTerrytheTerrible** [comment]
I've also been banned for no reason.

**Comment by Scarlette564** [comment]
What were your discord names?

**Comment by PazerOP** [comment]
@KingTerrytheTerrible sorry about that, you have been unbanned. @notroboot and @noneucat, can you please dm me on discord? My ID is pazer#8137.

About this PR, I specifically did not want to implement it this way because I was uncomfortable (as far as VAC goes) sending window messages directly to the game. I felt it was less suspicious to have the window messages come from a shipped hl2.exe.

**Comment by PazerOP** [comment]
also @CoolcGuy please dm me if you were also banned

**Comment by PazerOP** [comment]
This pull request is being closed because @notroboot is acting in bad faith and has many ties to cheaters.

**Pull request closed without merging**
